export function enhanceDossierUI(html) {
  const css = `<style>
.si-clickable{cursor:pointer;touch-action:manipulation}.si-clickable:hover{background:rgba(191,164,106,.055)}.si-clickable:focus{outline:2px solid var(--brass);outline-offset:-2px}.dossier-backdrop{position:fixed;inset:0;background:rgba(0,0,0,.62);backdrop-filter:blur(7px);z-index:1000;display:none;padding:18px}.dossier-backdrop.open{display:flex}.dossier{margin:auto;width:min(1050px,100%);max-height:calc(100vh - 36px);overflow:auto;background:#08120f;border:1px solid var(--brass);border-radius:20px;box-shadow:0 30px 90px rgba(0,0,0,.65);padding:20px}.dossier-head{display:flex;justify-content:space-between;gap:18px;align-items:flex-start;border-bottom:1px solid var(--line);padding-bottom:16px}.dossier-head h2{font-size:28px;margin:4px 0 6px;overflow-wrap:anywhere}.dossier-close{border:1px solid var(--line);background:#0a1412;color:var(--ink);border-radius:999px;padding:8px 12px;cursor:pointer}.dossier-metrics{grid-template-columns:repeat(4,1fr);margin:16px 0}.dossier-metric strong{display:block;font-size:25px;margin:4px 0}.dossier-metric span{color:var(--muted);font:11px/1.45 system-ui,sans-serif}.dossier-grid{display:grid;grid-template-columns:1fr 1fr;gap:14px}.dossier-card h3{margin:0 0 10px;font-size:18px}.dossier-list{margin:0;padding-left:18px;color:var(--muted);font:13px/1.6 system-ui,sans-serif}.assessment{border-left:3px solid var(--brass);padding:13px 15px;background:rgba(191,164,106,.06);font:13px/1.6 system-ui,sans-serif}.assessment strong{color:var(--ink)}.mini-table{width:100%;font-size:12px}.mini-table td,.mini-table th{padding:8px 6px}.dossier-link{color:var(--brass);text-decoration:none}.dossier-link:hover{text-decoration:underline}@media(max-width:760px){.dossier-backdrop{padding:8px}.dossier{max-height:calc(100vh - 16px);padding:15px}.dossier-grid{grid-template-columns:1fr}.dossier-metrics{grid-template-columns:1fr 1fr}.dossier-head h2{font-size:22px}}
</style>`;
  html=html.replace('</head>',css+'</head>');
  html=html.replace('<footer class="foot">','<div class="dossier-backdrop" id="dossierBackdrop" aria-hidden="true"><div class="dossier" role="dialog" aria-modal="true" aria-labelledby="dossierTitle"><div id="dossierBody"></div></div></div><footer class="foot">');
  const marker="document.querySelector('#refresh').addEventListener('click',load);";
  html=html.replace(marker,dossierScript()+'\n'+marker);
  return html;
}

function dossierScript(){return String.raw`
function dossierOpenPage(path){const d=window.__searchIntelligenceData;if(!d)return;const p=(d.pages||[]).find(x=>x.path===path);if(!p)return;const qs=(d.queries||[]).filter(x=>x.page===path).sort((a,b)=>b.impressions-a.impressions);const recs=(d.recommendations||[]).filter(x=>x.page===path);const link=recs.find(x=>x.context?.linkMap)?.context?.linkMap;const health=recs.find(x=>x.context?.siteHealth)?.context?.siteHealth;const near=qs.filter(x=>x.position>=8&&x.position<=20);const top10=qs.filter(x=>x.position>0&&x.position<=10);const rising=qs.filter(x=>x.positionChange>=2);const falling=qs.filter(x=>x.positionChange<=-2);let assessment='Stable organic presence. Continue monitoring before making broad editorial changes.',next='Preserve the page and supporting internal links.';if(health&&(!health.ok||!health.canonicalOk||!health.indexable)){assessment='Technical attention needed before editorial optimization.';next='Resolve the Site Health blocker first, then reassess Google performance.'}else if(recs[0]){assessment=recs[0].title+'. '+recs[0].rationale;next=recs[0].action}else if(near.length){assessment='Healthy page with page-one expansion opportunity. '+near.length+' query'+(near.length===1?' is':'ies are')+' currently near page one.';next=link&&link.inboundCount<4?'Strengthen internal linking before considering substantial content changes.':'Make only targeted refinements around the strongest near-page-one queries.'}
const linkSuggestions=link?.suggestions||[];const healthText=health?(health.ok?'Healthy':'Attention needed'):'No active Site Health check for this page';const html='<div class="dossier-head"><div><span class="eyebrow">Page Intelligence dossier</span><h2 id="dossierTitle">'+escapeHtml(path)+'</h2><a class="dossier-link" href="https://www.oceanliners.net'+encodeURI(path)+'" target="_blank" rel="noopener">Open live page ↗</a></div><button class="dossier-close" onclick="dossierClose()">Close</button></div><div class="grid dossier-metrics">'+dm('Clicks',fmt(p.clicks),pct(p.clicksChange||0)+' vs prior')+dm('Impressions',fmt(p.impressions),pct(p.trend||0)+' vs prior')+dm('CTR',Number(p.ctr||0).toFixed(2)+'%',signed(p.ctrChange||0)+' pts')+dm('Position','#'+Number(p.position||0).toFixed(1),signed(p.positionChange||0)+' places')+'</div><div class="assessment"><strong>CuratorOS assessment:</strong> '+escapeHtml(assessment)+'<br><strong>Recommended next move:</strong> '+escapeHtml(next)+'</div><div class="dossier-grid" style="margin-top:14px"><div class="card dossier-card"><h3>Search footprint</h3><ul class="dossier-list"><li>'+qs.length+' query/page pairs in the loaded Search Console dataset</li><li>'+top10.length+' ranking in the Top 10</li><li>'+near.length+' sitting at positions 8–20</li><li>'+rising.length+' materially rising · '+falling.length+' materially falling</li></ul></div><div class="card dossier-card"><h3>CuratorOS context</h3><ul class="dossier-list"><li>Link Map: '+(link?fmt(link.inboundCount)+' inbound / '+fmt(link.outboundCount)+' outbound'+(link.orphan?' · orphan risk':''):'No recommendation-level graph context loaded')+'</li><li>Site Health: '+escapeHtml(healthText)+(health?.issues?.length?' · '+health.issues.length+' issue(s)':'')+'</li><li>Current recommendations: '+recs.length+'</li></ul></div></div><div class="dossier-grid" style="margin-top:14px"><div class="card dossier-card"><h3>Strongest queries</h3>'+queryMiniTable(qs.slice(0,10))+'</div><div class="card dossier-card"><h3>Internal-link opportunities</h3>'+(linkSuggestions.length?'<ul class="dossier-list">'+linkSuggestions.slice(0,8).map(x=>'<li>'+escapeHtml(x.from)+(x.anchor?' — “'+escapeHtml(x.anchor)+'”':'')+'</li>').join('')+'</ul>':'<div class="empty-state">No Link Map suggestions are attached to the current recommendation set for this page.</div>')+'</div></div>';dossierShow(html)}
function dossierOpenQuery(query,page){const d=window.__searchIntelligenceData;if(!d)return;const rows=(d.queries||[]).filter(x=>x.query===query).sort((a,b)=>b.impressions-a.impressions);const x=rows.find(r=>r.page===page)||rows[0];if(!x)return;const rec=(d.recommendations||[]).find(r=>r.query===query&&r.page===x.page);const status=x.position<=3?'Top-3 winner':x.position<=10?'Page-one query':x.position<=20?'Near-page-one opportunity':'Developing visibility';const action=rec?.action||(x.position<=10?'Protect the ranking; avoid unnecessary rewrites.':'Monitor movement and strengthen relevance/internal support if the query continues gaining impressions.');const html='<div class="dossier-head"><div><span class="eyebrow">Query Intelligence dossier</span><h2 id="dossierTitle">'+escapeHtml(query)+'</h2><span class="workspace-note">Primary destination: '+escapeHtml(x.page)+'</span></div><button class="dossier-close" onclick="dossierClose()">Close</button></div><div class="grid dossier-metrics">'+dm('Clicks',fmt(x.clicks),pct(x.clicksChange||0)+' vs prior')+dm('Impressions',fmt(x.impressions),pct(x.impressionChange||0)+' vs prior')+dm('CTR',Number(x.ctr||0).toFixed(2)+'%',signed(x.ctrChange||0)+' pts')+dm('Position','#'+Number(x.position||0).toFixed(1),signed(x.positionChange||0)+' places')+'</div><div class="assessment"><strong>CuratorOS assessment:</strong> '+escapeHtml(status)+(x.isNew?' · Newly visible in this comparison period.':'')+(x.enteredTop10?' · Entered the Top 10.':'')+(x.leftTop10?' · Fell out of the Top 10.':'')+'<br><strong>Recommended next move:</strong> '+escapeHtml(action)+'</div><div class="dossier-grid" style="margin-top:14px"><div class="card dossier-card"><h3>Ranking trajectory</h3><ul class="dossier-list"><li>Previous position: '+(x.previousPosition?'#'+Number(x.previousPosition).toFixed(1):'not visible')+'</li><li>Current position: #'+Number(x.position||0).toFixed(1)+'</li><li>Previous impressions: '+fmt(x.previousImpressions)+'</li><li>Current impressions: '+fmt(x.impressions)+'</li></ul></div><div class="card dossier-card"><h3>Destination pages</h3>'+queryMiniTable(rows)+'</div></div>';dossierShow(html)}
function dm(label,value,note){return '<div class="card dossier-metric"><span class="eyebrow">'+label+'</span><strong>'+value+'</strong><span>'+note+'</span></div>'}
function queryMiniTable(rows){if(!rows.length)return '<div class="empty-state">No query data in the current loaded period.</div>';return '<div style="overflow:auto"><table class="mini-table"><thead><tr><th>Query / page</th><th class="num">Impr.</th><th class="num">Pos.</th></tr></thead><tbody>'+rows.map(x=>'<tr class="si-clickable" tabindex="0" data-dossier-query="'+escapeHtml(x.query)+'" data-dossier-page="'+escapeHtml(x.page)+'"><td>'+escapeHtml(x.query||x.page)+'</td><td class="num">'+fmt(x.impressions)+'</td><td class="num">#'+Number(x.position||0).toFixed(1)+'</td></tr>').join('')+'</tbody></table></div>'}
function dossierShow(html){const b=document.querySelector('#dossierBackdrop');document.querySelector('#dossierBody').innerHTML=html;b.classList.add('open');b.setAttribute('aria-hidden','false');document.body.style.overflow='hidden'}
function dossierClose(){const b=document.querySelector('#dossierBackdrop');b.classList.remove('open');b.setAttribute('aria-hidden','true');document.body.style.overflow=''}
document.addEventListener('click',e=>{const page=e.target.closest('[data-dossier-page-only]');if(page){dossierOpenPage(page.dataset.dossierPageOnly);return}const q=e.target.closest('[data-dossier-query]');if(q){dossierOpenQuery(q.dataset.dossierQuery,q.dataset.dossierPage);return}if(e.target.id==='dossierBackdrop')dossierClose()});document.addEventListener('keydown',e=>{if(e.key==='Escape')dossierClose();if(e.key==='Enter'){const p=e.target.closest('[data-dossier-page-only]');if(p)dossierOpenPage(p.dataset.dossierPageOnly);const q=e.target.closest('[data-dossier-query]');if(q)dossierOpenQuery(q.dataset.dossierQuery,q.dataset.dossierPage)}});
`;}
