export function enhanceIndexMonitorUI(html){
  const css=`<style>
.index-actions{display:flex;gap:9px;flex-wrap:wrap;align-items:center;margin-top:14px}.index-actions input{flex:1;min-width:240px}.index-results{margin-top:14px}.index-row{display:grid;grid-template-columns:1.2fr .7fr .8fr .8fr;gap:10px;padding:12px 0;border-bottom:1px solid rgba(191,164,106,.14);font:12px/1.45 system-ui,sans-serif}.index-row strong{overflow-wrap:anywhere}.index-good{color:var(--good)}.index-bad{color:var(--bad)}.index-muted{color:var(--muted)}@media(max-width:760px){.index-row{grid-template-columns:1fr 1fr}.index-row strong{grid-column:1/-1}}
</style>`;html=html.replace('</head>',css+'</head>');
  const old='<div class="workspace" data-workspace-panel="index"><section><div class="section-head"><div><span class="eyebrow">Index Monitor</span><h2>Search visibility watch</h2></div><p>Signals available now; URL Inspection can be added next.</p></div><div class="grid signal-grid" id="indexWorkspace"></div><div class="card empty-state" style="margin-top:14px">This workspace currently uses Search Console visibility as an index-presence signal. The next backend phase can add Google URL Inspection for explicit indexed / not-indexed state and canonical diagnostics.</div></section></div>';
  const replacement='<div class="workspace" data-workspace-panel="index"><section><div class="section-head"><div><span class="eyebrow">Index Monitor</span><h2>Google index inspection</h2></div><p>Explicit index/canonical data from Search Console URL Inspection.</p></div><div class="grid signal-grid" id="indexWorkspace"></div><div class="card" style="margin-top:14px"><div class="workspace-toolbar"><input id="inspectionUrl" class="workspace-search" type="text" placeholder="/ships/rms-olympic or full oceanliners.net URL"><div class="index-actions"><button class="btn" id="inspectManual">Inspect URL</button><button class="btn" id="inspectPriority">Inspect priority pages</button></div></div><div class="workspace-note" id="inspectionStatus">Inspection runs only when requested.</div><div class="index-results" id="inspectionResults"></div></div></section></div>';
  html=html.replace(old,replacement);
  const marker="document.querySelector('#refresh').addEventListener('click',load);";
  html=html.replace(marker,indexScript()+'\n'+marker);return html;
}
function indexScript(){return String.raw`
async function runUrlInspection(urls){const status=document.querySelector('#inspectionStatus');const box=document.querySelector('#inspectionResults');status.textContent='Inspecting '+urls.length+' URL'+(urls.length===1?'':'s')+' with Google…';box.innerHTML='';try{const r=await fetch('/api/url-inspection',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({urls})});const d=await r.json();if(!r.ok||!d.ok)throw new Error(d.error||'URL Inspection failed');status.textContent='Google inspected '+d.checkedUrlCount+' URL'+(d.checkedUrlCount===1?'':'s')+'.';box.innerHTML=(d.results||[]).map(renderInspectionRow).join('')||'<div class="empty-state">No inspection results returned.</div>'}catch(e){status.textContent='Inspection failed: '+e.message;box.innerHTML='<div class="empty-state">'+escapeHtml(e.message)+'</div>'}}
function renderInspectionRow(x){if(!x.ok)return '<div class="index-row"><strong>'+escapeHtml(x.path||x.url)+'</strong><span class="index-bad">Error</span><span class="index-muted">—</span><span class="index-muted">'+escapeHtml(x.error||'Unknown error')+'</span></div>';const pass=String(x.verdict||'').toUpperCase()==='PASS';const canon=x.googleCanonical||x.userCanonical||'—';return '<div class="index-row"><strong class="si-clickable" tabindex="0" data-dossier-page-only="'+escapeHtml(x.path)+'">'+escapeHtml(x.path)+'</strong><span class="'+(pass?'index-good':'index-bad')+'">'+escapeHtml(x.verdict||'Unknown')+'</span><span>'+escapeHtml(x.coverageState||x.indexingState||'Unknown')+'</span><span class="index-muted">'+escapeHtml(canon)+'</span></div>'}
function priorityInspectionUrls(){const d=window.__searchIntelligenceData||{};const seen=new Set(),out=[];for(const x of [...(d.today||[]),...(d.recommendations||[])]){const p=x.page;if(!p||seen.has(p))continue;seen.add(p);out.push('https://www.oceanliners.net'+p);if(out.length>=8)break}return out}
document.querySelector('#inspectManual')?.addEventListener('click',()=>{const v=document.querySelector('#inspectionUrl').value.trim();if(!v)return;runUrlInspection([v])});document.querySelector('#inspectPriority')?.addEventListener('click',()=>{const urls=priorityInspectionUrls();if(urls.length)runUrlInspection(urls);else document.querySelector('#inspectionStatus').textContent='No priority pages are available in the current dataset.'});
`;}
