export function enhanceInterventionUI(html){
  const css=`<style>
.intervention-grid{display:grid;grid-template-columns:repeat(2,1fr);gap:14px;margin-top:14px}.intervention-table-wrap{overflow:auto}.intervention-confidence{display:inline-block;border:1px solid var(--line);border-radius:999px;padding:3px 7px;font:700 10px system-ui,sans-serif;text-transform:uppercase;letter-spacing:.06em}.intervention-confidence.strong{color:var(--good);border-color:rgba(147,197,158,.5)}.intervention-confidence.early{color:var(--brass)}.intervention-confidence.insufficient{color:var(--muted)}.learning-note{padding:14px;border-left:3px solid var(--brass);background:rgba(191,164,106,.05);font:13px/1.6 system-ui,sans-serif}.learning-note strong{color:var(--ink)}@media(max-width:800px){.intervention-grid{grid-template-columns:1fr}}
</style>`;
  html=html.replace('</head>',css+'</head>');
  const outcomesTab='<button class="tab" data-workspace="outcomes" role="tab" aria-selected="false">Outcomes</button>';
  html=html.replace(outcomesTab,outcomesTab+'<button class="tab" data-workspace="interventions" role="tab" aria-selected="false">Interventions</button>');
  const footer='<footer class="foot">';
  const panel='<div class="workspace" data-workspace-panel="interventions"><section><div class="section-head"><div><span class="eyebrow">Intervention Intelligence</span><h2>What actually works here?</h2></div><p>CuratorOS learns from implemented recommendations without overclaiming from small samples.</p></div><div class="grid signal-grid" id="interventionSummary"></div><div class="learning-note" id="interventionHeadline" style="margin-top:14px">Waiting for enough implemented outcomes to identify reliable patterns.</div><div class="intervention-grid"><div class="card"><div class="section-head" style="margin-top:0"><div><span class="eyebrow">By intervention</span><h2>Recommendation types</h2></div></div><div class="intervention-table-wrap"><table><thead><tr><th>Type</th><th class="num">Evaluated</th><th class="num">Improved</th><th class="num">Success</th><th class="num">Median rank lift</th><th>Confidence</th></tr></thead><tbody id="interventionTypeRows"></tbody></table></div></div><div class="card"><div class="section-head" style="margin-top:0"><div><span class="eyebrow">By page family</span><h2>Where changes respond</h2></div></div><div class="intervention-table-wrap"><table><thead><tr><th>Family</th><th class="num">Evaluated</th><th class="num">Improved</th><th class="num">Success</th><th class="num">Median rank lift</th><th>Confidence</th></tr></thead><tbody id="interventionFamilyRows"></tbody></table></div></div></div><div class="card" style="margin-top:14px"><div class="section-head" style="margin-top:0"><div><span class="eyebrow">Learning guardrails</span><h2>How CuratorOS uses this evidence</h2></div></div><div id="interventionGuardrails" class="workspace-note"></div></div></section></div>';
  html=html.replace(footer,panel+footer);
  const valid="['overview','opportunities','pages','queries','index','technical','outcomes']";
  html=html.replace(valid,"['overview','opportunities','pages','queries','index','technical','outcomes','interventions']");
  const marker="document.querySelector('#refresh').addEventListener('click',load);";
  html=html.replace(marker,interventionScript()+'\n'+marker);
  return html;
}

function interventionScript(){return String.raw`
function interventionType(x){const t=((x.recommendation||'')+' '+(x.notes||'')).toLowerCase();if(t.includes('site health')||t.includes('canonical')||t.includes('technical blocker')||t.includes('index'))return 'Technical fix';if(t.includes('internal link')||t.includes('linking pages')||t.includes('internal support'))return 'Internal linking';if(t.includes('rewrite')||t.includes('content')||t.includes('refinement')||t.includes('title')||t.includes('ctr'))return 'Content refinement';if(t.includes('protect')||t.includes('leave it alone')||t.includes('no editorial action')||t.includes('avoid unnecessary'))return 'Protect / preserve';return 'Other intervention'}
function pageFamily(path){path=String(path||'');if(path.startsWith('/ships/'))return 'Ship guides';if(path.includes('titanic')||path.startsWith('/why-')||path.startsWith('/what-')||path.startsWith('/how-')||path.startsWith('/did-')||path.startsWith('/could-'))return 'Quick answers / features';if(path.startsWith('/collections/')||path.includes('/hub')||path==='/explore'||path==='/ships/ships')return 'Hubs / collections';return 'Other pages'}
function median(values){const a=values.filter(Number.isFinite).sort((a,b)=>a-b);if(!a.length)return null;const m=Math.floor(a.length/2);return a.length%2?a[m]:(a[m-1]+a[m])/2}
function learningConfidence(n){if(n>=8)return{label:'strong',className:'strong'};if(n>=3)return{label:'early',className:'early'};return{label:'insufficient',className:'insufficient'}}
function aggregateInterventions(records,keyFn){const groups=new Map();for(const x of records){const ev=evaluateOutcome(x);if(!ev.current||!['improved','neutral','declined'].includes(ev.state))continue;const key=keyFn(x);if(!groups.has(key))groups.set(key,[]);groups.get(key).push({x,ev})}return [...groups.entries()].map(([name,items])=>{const improved=items.filter(y=>y.ev.state==='improved').length;const declined=items.filter(y=>y.ev.state==='declined').length;const neutral=items.filter(y=>y.ev.state==='neutral').length;const lifts=items.map(y=>Number(y.ev.pos||0));const clicks=items.map(y=>Number(y.ev.clicks||0));return{name,evaluated:items.length,improved,declined,neutral,success:items.length?improved/items.length*100:0,medianRank:median(lifts),medianClicks:median(clicks),confidence:learningConfidence(items.length)}}).sort((a,b)=>b.evaluated-a.evaluated||b.success-a.success)}
function interventionRow(x){return '<tr><td>'+escapeHtml(x.name)+'</td><td class="num">'+x.evaluated+'</td><td class="num">'+x.improved+'</td><td class="num">'+x.success.toFixed(0)+'%</td><td class="num '+deltaClass(x.medianRank||0)+'">'+(x.medianRank==null?'—':signed(x.medianRank))+'</td><td><span class="intervention-confidence '+x.confidence.className+'">'+x.confidence.label+'</span></td></tr>'}
function renderInterventionIntelligence(){const records=(window.__outcomes||[]).filter(x=>x.status==='implemented');const evaluated=records.map(x=>({x,ev:evaluateOutcome(x)})).filter(y=>y.ev.current&&['improved','neutral','declined'].includes(y.ev.state));const improved=evaluated.filter(y=>y.ev.state==='improved').length,declined=evaluated.filter(y=>y.ev.state==='declined').length,neutral=evaluated.filter(y=>y.ev.state==='neutral').length;const overall=evaluated.length?improved/evaluated.length*100:0;document.querySelector('#interventionSummary').innerHTML=[['Evaluated',evaluated.length,'Implemented changes old enough for comparison'],['Improved',improved,'Outcomes beating their saved baseline'],['Neutral',neutral,'No material directional change'],['Declined',declined,'Outcomes currently below baseline']].map(x=>'<div class="card signal-card"><span class="eyebrow">'+x[0]+'</span><strong>'+x[1]+'</strong><span>'+x[2]+'</span></div>').join('');const byType=aggregateInterventions(records,interventionType),byFamily=aggregateInterventions(records,x=>pageFamily(x.page));document.querySelector('#interventionTypeRows').innerHTML=byType.length?byType.map(interventionRow).join(''):'<tr><td colspan="6" class="empty-state">No mature interventions yet.</td></tr>';document.querySelector('#interventionFamilyRows').innerHTML=byFamily.length?byFamily.map(interventionRow).join(''):'<tr><td colspan="6" class="empty-state">No mature page-family outcomes yet.</td></tr>';const headline=document.querySelector('#interventionHeadline');if(evaluated.length<3){headline.innerHTML='<strong>Not enough evidence yet.</strong> CuratorOS will not adjust recommendation behavior from fewer than three comparable mature outcomes.'}else{const eligible=byType.filter(x=>x.evaluated>=3).sort((a,b)=>b.success-a.success);if(eligible.length){const best=eligible[0];headline.innerHTML='<strong>Early learning:</strong> '+escapeHtml(best.name)+' currently has a '+best.success.toFixed(0)+'% improvement rate across '+best.evaluated+' evaluated interventions'+(best.medianRank!=null?', with a median ranking lift of '+signed(best.medianRank)+' places':'')+'.'}else{headline.innerHTML='<strong>Evidence is accumulating.</strong> Overall, '+overall.toFixed(0)+'% of mature tracked interventions are currently classified as improved, but no intervention category has three comparable outcomes yet.'}}document.querySelector('#interventionGuardrails').innerHTML='CuratorOS treats 1–2 outcomes as anecdotal, 3–7 as early directional evidence, and 8+ as stronger site-specific evidence. Declines are retained rather than discarded. Recommendations should only be reweighted after repeated comparable outcomes, and correlation is not treated as proof that a single edit caused the ranking change.'}
const oldRenderOutcomes=renderOutcomes;renderOutcomes=function(){oldRenderOutcomes();renderInterventionIntelligence()};
setTimeout(()=>{if(window.__outcomes)renderInterventionIntelligence()},0);
`;}
