export function enhanceWorkspaceUI(html) {
  const css = `<style>
.workspace{display:none}.workspace.active{display:block}.workspace-toolbar{display:flex;gap:10px;align-items:center;justify-content:space-between;flex-wrap:wrap;margin:0 0 14px}.workspace-search{min-width:240px;flex:1;max-width:520px;border:1px solid var(--line);background:#0a1412;color:var(--ink);border-radius:999px;padding:10px 14px;font:600 13px system-ui,sans-serif}.workspace-note{color:var(--muted);font:12px/1.5 system-ui,sans-serif}.signal-grid{grid-template-columns:repeat(3,1fr)}.signal-card strong{display:block;font-size:26px;margin:5px 0}.signal-card span{color:var(--muted);font:12px/1.45 system-ui,sans-serif}.empty-state{padding:24px;color:var(--muted);font:13px/1.6 system-ui,sans-serif}.tab{cursor:pointer;touch-action:manipulation}.tab:focus-visible{outline:2px solid var(--brass);outline-offset:2px}@media(max-width:760px){.signal-grid{grid-template-columns:1fr}.workspace-search{min-width:100%}}
</style>`;
  html = html.replace('</head>', css + '</head>');
  const oldTabs = '<div class="tabs"><button class="tab active">Overview</button><button class="tab">Opportunities</button><button class="tab">Pages</button><button class="tab">Queries</button><button class="tab">Index Monitor</button><button class="tab">Technical</button></div>';
  const tabs = '<div class="tabs" role="tablist" aria-label="Search Intelligence workspaces"><button class="tab active" data-workspace="overview" role="tab" aria-selected="true">Overview</button><button class="tab" data-workspace="opportunities" role="tab" aria-selected="false">Opportunities</button><button class="tab" data-workspace="pages" role="tab" aria-selected="false">Pages</button><button class="tab" data-workspace="queries" role="tab" aria-selected="false">Queries</button><button class="tab" data-workspace="index" role="tab" aria-selected="false">Index Monitor</button><button class="tab" data-workspace="technical" role="tab" aria-selected="false">Technical</button></div>';
  html = html.replace(oldTabs, tabs);
  const start = '<div class="grid layout">'; html = html.replace(start, '<div class="workspace active" data-workspace-panel="overview">' + start);
  const pageSection = '<section><div class="section-head"><div><span class="eyebrow">Page intelligence</span><h2>Pages gaining and losing visibility</h2></div><p>Compared with the immediately preceding period.</p></div><div class="card" style="overflow:auto"><table><thead><tr><th>Page</th><th style="text-align:right">Clicks</th><th style="text-align:right">Impressions</th><th style="text-align:right">CTR</th><th style="text-align:right">Position</th><th style="text-align:right">Visibility</th><th style="text-align:right">Rank Δ</th></tr></thead><tbody id="pages"></tbody></table></div></section>';
  html = html.replace(pageSection, pageSection + '</div>' + workspaceMarkup());
  const hook = "document.querySelector('#pages').innerHTML=(d.pages||[]).slice(0,50).map(x=>'<tr><td>'+escapeHtml(x.path)+'</td><td class=\"num\">'+fmt(x.clicks)+'</td><td class=\"num\">'+fmt(x.impressions)+'</td><td class=\"num\">'+x.ctr.toFixed(2)+'%</td><td class=\"num\">'+x.position.toFixed(1)+'</td><td class=\"num '+deltaClass(x.trend||0)+'\">'+pct(x.trend||0)+'</td><td class=\"num '+deltaClass(x.positionChange||0)+'\">'+signed(x.positionChange||0)+'</td></tr>').join('');";
  html = html.replace(hook, hook + '\n  window.__searchIntelligenceData=d;renderWorkspaceData(d);');
  const scriptEnd = "document.querySelector('#refresh').addEventListener('click',load);document.querySelector('#period').addEventListener('change',load);load();"; html = html.replace(scriptEnd, workspaceScript() + '\n' + scriptEnd); return html;
}
function workspaceMarkup(){return `
<div class="workspace" data-workspace-panel="opportunities"><section><div class="section-head"><div><span class="eyebrow">Opportunities</span><h2>Full action queue</h2></div><p>Ranked by CuratorOS priority, confidence, and upside.</p></div><div class="workspace-toolbar"><input id="opportunitySearch" class="workspace-search" type="search" placeholder="Filter by query, page, action…"><span class="workspace-note" id="opportunityCount"></span></div><div class="card" id="opportunityWorkspace"></div></section></div>
<div class="workspace" data-workspace-panel="pages"><section><div class="section-head"><div><span class="eyebrow">Pages</span><h2>Page intelligence</h2></div><p>Tap any page to open its complete intelligence dossier.</p></div><div class="workspace-toolbar"><input id="pageSearch" class="workspace-search" type="search" placeholder="Filter pages…"><span class="workspace-note" id="pageCount"></span></div><div class="card" style="overflow:auto"><table><thead><tr><th>Page</th><th class="num">Clicks</th><th class="num">Impressions</th><th class="num">CTR</th><th class="num">Position</th><th class="num">Visibility</th><th class="num">Rank Δ</th></tr></thead><tbody id="pageWorkspace"></tbody></table></div></section></div>
<div class="workspace" data-workspace-panel="queries"><section><div class="section-head"><div><span class="eyebrow">Queries</span><h2>Google query intelligence</h2></div><p>Tap a query to open its ranking dossier.</p></div><div class="workspace-toolbar"><input id="querySearch" class="workspace-search" type="search" placeholder="Filter queries or pages…"><span class="workspace-note" id="queryCount"></span></div><div class="card" style="overflow:auto"><table><thead><tr><th>Query</th><th>Page</th><th class="num">Clicks</th><th class="num">Impressions</th><th class="num">CTR</th><th class="num">Position</th><th class="num">Rank Δ</th></tr></thead><tbody id="queryWorkspace"></tbody></table></div></section></div>
<div class="workspace" data-workspace-panel="index"><section><div class="section-head"><div><span class="eyebrow">Index Monitor</span><h2>Search visibility watch</h2></div><p>Signals available now; URL Inspection can be added next.</p></div><div class="grid signal-grid" id="indexWorkspace"></div><div class="card empty-state" style="margin-top:14px">This workspace currently uses Search Console visibility as an index-presence signal. The next backend phase can add Google URL Inspection for explicit indexed / not-indexed state and canonical diagnostics.</div></section></div>
<div class="workspace" data-workspace-panel="technical"><section><div class="section-head"><div><span class="eyebrow">Technical</span><h2>CuratorOS technical context</h2></div><p>Live integration state and blockers affecting active recommendations.</p></div><div class="grid signal-grid" id="technicalWorkspace"></div><div class="card" style="margin-top:14px" id="technicalIssues"></div></section></div>`;}
function workspaceScript(){return String.raw`
function setWorkspace(name,push=true){const valid=['overview','opportunities','pages','queries','index','technical'];if(!valid.includes(name))name='overview';document.querySelectorAll('.tab[data-workspace]').forEach(b=>{const on=b.dataset.workspace===name;b.classList.toggle('active',on);b.setAttribute('aria-selected',on?'true':'false')});document.querySelectorAll('[data-workspace-panel]').forEach(p=>p.classList.toggle('active',p.dataset.workspacePanel===name));if(push){const u=new URL(location.href);u.searchParams.set('view',name);history.replaceState(null,'',u)}}
function renderWorkspaceData(d){renderOpportunities(d);renderPagesWorkspace(d);renderQueriesWorkspace(d);renderIndexWorkspace(d);renderTechnicalWorkspace(d)}
function renderOpportunities(d){const q=(document.querySelector('#opportunitySearch')?.value||'').toLowerCase();const all=d.recommendations||[];const rows=all.filter(x=>!q||[x.query,x.page,x.title,x.action,x.type].join(' ').toLowerCase().includes(q));document.querySelector('#opportunityCount').textContent=rows.length+' of '+all.length+' recommendations';document.querySelector('#opportunityWorkspace').innerHTML=rows.map(x=>'<article class="rec"><div class="badge">'+escapeHtml((x.type||'•').slice(0,1).toUpperCase())+'</div><div><h3>'+escapeHtml(x.title)+'</h3><p><strong class="si-clickable" tabindex="0" data-dossier-query="'+escapeHtml(x.query)+'" data-dossier-page="'+escapeHtml(x.page)+'">'+escapeHtml(x.query)+'</strong> · <span class="si-clickable" tabindex="0" data-dossier-page-only="'+escapeHtml(x.page)+'">'+escapeHtml(x.page)+'</span><br>'+escapeHtml((x.evidence||[]).join(' · '))+'<br><strong>Next:</strong> '+escapeHtml(x.action)+'</p></div><div class="stat">'+fmt(x.priorityScore)+'/100<small>'+escapeHtml(x.confidence||'')+' confidence · '+escapeHtml(x.expectedUpside||'')+' upside</small></div></article>').join('')||'<div class="empty-state">No recommendations match this filter.</div>'}
function renderPagesWorkspace(d){const q=(document.querySelector('#pageSearch')?.value||'').toLowerCase();const all=d.pages||[];const rows=all.filter(x=>!q||String(x.path).toLowerCase().includes(q));document.querySelector('#pageCount').textContent=rows.length+' of '+all.length+' pages';document.querySelector('#pageWorkspace').innerHTML=rows.map(x=>'<tr class="si-clickable" tabindex="0" data-dossier-page-only="'+escapeHtml(x.path)+'"><td>'+escapeHtml(x.path)+'</td><td class="num">'+fmt(x.clicks)+'</td><td class="num">'+fmt(x.impressions)+'</td><td class="num">'+Number(x.ctr||0).toFixed(2)+'%</td><td class="num">'+Number(x.position||0).toFixed(1)+'</td><td class="num '+deltaClass(x.trend||0)+'">'+pct(x.trend||0)+'</td><td class="num '+deltaClass(x.positionChange||0)+'">'+signed(x.positionChange||0)+'</td></tr>').join('')||'<tr><td colspan="7" class="empty-state">No pages match this filter.</td></tr>'}
function renderQueriesWorkspace(d){const q=(document.querySelector('#querySearch')?.value||'').toLowerCase();const all=d.queries||[];const rows=all.filter(x=>!q||[x.query,x.page].join(' ').toLowerCase().includes(q));document.querySelector('#queryCount').textContent=rows.length+' of '+all.length+' query/page pairs';document.querySelector('#queryWorkspace').innerHTML=rows.map(x=>'<tr class="si-clickable" tabindex="0" data-dossier-query="'+escapeHtml(x.query)+'" data-dossier-page="'+escapeHtml(x.page)+'"><td>'+escapeHtml(x.query)+'</td><td>'+escapeHtml(x.page)+'</td><td class="num">'+fmt(x.clicks)+'</td><td class="num">'+fmt(x.impressions)+'</td><td class="num">'+Number(x.ctr||0).toFixed(2)+'%</td><td class="num">'+Number(x.position||0).toFixed(1)+'</td><td class="num '+deltaClass(x.positionChange||0)+'">'+signed(x.positionChange||0)+'</td></tr>').join('')||'<tr><td colspan="7" class="empty-state">No queries match this filter.</td></tr>'}
function renderIndexWorkspace(d){const q=d.queries||[];const visiblePages=new Set(q.filter(x=>x.impressions>0).map(x=>x.page)).size;const newQueries=q.filter(x=>x.isNew).length;const top10=q.filter(x=>x.position>0&&x.position<=10).length;document.querySelector('#indexWorkspace').innerHTML=[['Visible pages',visiblePages,'Pages represented in current Search Console query data'],['New query/page pairs',newQueries,'Pairs with impressions now and none in the prior comparison period'],['Top-10 pairs',top10,'Current query/page pairs ranking on page one']].map(x=>'<div class="card signal-card"><span class="eyebrow">'+x[0]+'</span><strong>'+fmt(x[1])+'</strong><span>'+x[2]+'</span></div>').join('')}
function renderTechnicalWorkspace(d){const cx=d.curatorContext||{};const recs=[...(d.recommendations||[]),...(d.today||[])];const blockers=[];const seen=new Set();recs.forEach(x=>{const h=x.context&&x.context.siteHealth;if(!h||h.ok||seen.has(x.page))return;seen.add(x.page);blockers.push({page:x.page,issues:h.issues||[],status:h.httpStatus})});document.querySelector('#technicalWorkspace').innerHTML=[['Link Map',cx.linkMap?.ok?'Connected':'Unavailable',cx.linkMap?.error||'Internal-link context for recommendations'],['Site Health',cx.siteHealth?.ok?'Connected':'Unavailable',cx.siteHealth?.error||((cx.siteHealth?.checkedPageCount||0)+' active pages checked')],['Technical blockers',blockers.length,'Active recommendation pages requiring technical attention']].map(x=>'<div class="card signal-card"><span class="eyebrow">'+escapeHtml(x[0])+'</span><strong>'+escapeHtml(x[1])+'</strong><span>'+escapeHtml(x[2])+'</span></div>').join('');document.querySelector('#technicalIssues').innerHTML=blockers.length?blockers.map(x=>'<article class="rec"><div class="badge">!</div><div><h3 class="si-clickable" tabindex="0" data-dossier-page-only="'+escapeHtml(x.page)+'">'+escapeHtml(x.page)+'</h3><p>'+escapeHtml((x.issues||[]).join(' · ')||('HTTP '+(x.status||'issue detected')))+'</p></div></article>').join(''):'<div class="empty-state">No technical blockers were found among the active recommendation pages checked by Site Health.</div>'}
document.querySelectorAll('.tab[data-workspace]').forEach(b=>b.addEventListener('click',()=>setWorkspace(b.dataset.workspace)));['opportunitySearch','pageSearch','querySearch'].forEach(id=>document.querySelector('#'+id)?.addEventListener('input',()=>window.__searchIntelligenceData&&renderWorkspaceData(window.__searchIntelligenceData)));setWorkspace(new URL(location.href).searchParams.get('view')||'overview',false);
`;}
